---
- name: Configure Maximal Workers/Bulk Actions in Proxmox
  ansible.builtin.lineinfile:
    path: /etc/pve/datacenter.cfg
    regexp: "^max_workers:.*"
    line: "max_workers: {{ max_workers }}"
    create: true
    mode: '0640'

- name: Install Proxmox packages
  ansible.builtin.apt:
    name:
      - python3-proxmoxer
      - proxmox-ve
      - pve-headers
      - pve-qemu-kvm
      - pve-container
      - pve-manager
    update_cache: true
    state: present

- name: Ensure Proxmox services are running
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - pvedaemon
    - pve-cluster
    - pve-manager
    - pveproxy
    - pvestatd

